name: ci

jobs:
  specs:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ruby:
          - '2.7'
          - '2.6'
        include:
          - ruby: '2.7'
            coverage: 'true'

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Install package dependencies
        run: "[ -e $APT_DEPS ] || sudo apt-get install -y --no-install-recommends $APT_DEPS"
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{matrix.ruby}}
      - name: Install latest bundler
        run: |
          gem install bundler --no-document
      - name: Bundle install
        env:
          DIFFEND_DEVELOPMENT: true
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: Run all tests
        env:
          GITHUB_COVERAGE: ${{matrix.coverage}}
        run: bundle exec rspec

on:
  push:
  schedule:
    - cron:  '0 1 * * *'
